-- AlterTable (pv=RVI e ipi=RVF: Decimal -> String para FEITO/PENDENTE)
ALTER TABLE "pleitos" ALTER COLUMN "pv" DROP DEFAULT;
ALTER TABLE "pleitos" ALTER COLUMN "pv" TYPE TEXT USING NULL;
ALTER TABLE "pleitos" ALTER COLUMN "ipi" DROP DEFAULT;
ALTER TABLE "pleitos" ALTER COLUMN "ipi" TYPE TEXT USING NULL;
